server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/2022-6-1
    username: root
    password: 1234

string:
  str1: Hello \n World
  str2: 'Hello \n World'
  str3: "Hello \n World"


#student:
#  id: 1
#  name: zhangsan
#  age: 18

student: {id: 1,name: zhangsan,age: 19}


#mylist:
#  colors:
#    - RED
#    - GREEN
#    - BLACK
#    - WHITE
#    - YELLOW

mylist: {colors: [RED,GREEN,BLACK,WHITE,YELLOW]}

logging:
  file:
    path: D:/logs/spring.log
  level:
    root: error
